theme: jekyll-theme-cayman
title: Kapanin
description: Kapanin merupakan aplikasi berbasis AI yang membantu pemilik toko menentukan kapan dan berapa besar diskon yang perlu diberikan berdasarkan data penjualan dan kondisi stok.